#ifndef DOCUMENT_H
#define DOCUMENT_H

#include <string>

std::string  documents = "# General Information"
                         "The Shams Pasargad Power Plant, formerly known as Andisheh Sazan Bahin Samad, owns the Shariati Power Plant, which covers an area of 32.5 hectares."
                         "The power plant has a total nominal capacity of 501.3 MW under ISO conditions."
                         "It consists of 2 gas units (F9) with a capacity of 123.4 MW each, 1 steam unit with a capacity of 104.5 MW, and 6 gas units (F5) with a capacity of 25 MW each."
                         "# Operational Units"
                         "The operational units include:"
                         "- Two gas units (F5) with a capacity of 25 MW each, operational since 1363/04, manufactured by Hitachi."
                         "- Two gas units (F5) with a capacity of 25 MW each, operational since 1363/10, manufactured by Hitachi."
                         "- Two gas units (F5) with a capacity of 25 MW each, operational since 1365/05 and 1365/09, manufactured by Hitachi."
                         "- Two gas units (F9) with a capacity of 123.4 MW each, operational since 1373/10, manufactured by John Brown."
                         "- One steam unit with a capacity of 104.5 MW, operational since 1382/01, manufactured by Siemens."
                         "# Technical Details of F5 Gas Units"
                         "The F5 gas units have turbines with 2 stages, each consisting of a row of stationary and moving blades."
                         "The compressor in F5 units has 16 stages, each consisting of a row of stationary and moving blades."
                         "Each F5 gas unit has 10 combustion chambers around the compressor outlet."
                         "The generator in F5 units is a single-pair pole type with a nominal capacity of 27.87 MVA and an output voltage of 11.5 kV."
                         "# Technical Details of F9 Gas Units"
                         "The F9 gas units have turbines with 3 stages, each consisting of a row of stationary and moving blades."
                         "The compressor in F9 units is of axial flow type with 17 stages, each consisting of a row of stationary and moving blades."
                         "Each F9 gas unit has 14 combustion chambers around the compressor outlet, including injectors, liners, transition pieces, cross-fire tubes, spark plugs, and flame detectors."
                         "The generator in F9 units is a single-pair pole type with a nominal capacity of 157.87 MVA and an output voltage of 13.8 kV."
                         "# Steam Unit Details"
                         "The steam unit has a Siemens E-Type turbine with a nominal power of 104.57 MW."
                         "The steam turbine has two stages: LP (7 rows of blades) and HP (27 rows of blades)."
                         "The steam turbine has two steam inlets (HP) and one steam inlet (IP)."
                         "The generator in the steam unit is a single-pole type with an output voltage of 10.5 kV and an apparent power of 125 MVA."
                         "Water for the power plant is supplied via two wells and transported to the treatment plant through two pipelines."
                         "# Shariati Substation"
                         "The Shariati Substation covers an area of 13.5 hectares and is one of the most important high-voltage stations in the Khorasan network and Mashhad."
                         "The substation has two three-winding transformers with a nominal capacity of 90 MVA and a conversion ratio of 20/63/132 kV."
                         "The substation transmits electricity generated by the Shariati Power Plant to the 132 kV network and supplies power to important substations such as Kuhsangi and Khajeh Rabi."
                         "The substation also supplies power to 5 double-circuit 132 kV lines feeding substations in Sarakhs, Dosty Dam pumping stations, Attar Neyshabur, Iran Khodro, and Sahil Borj Neyshabur."
                         "In the 63 kV network, the substation supplies power to Dizbad, Silo, Rezvan, Mashhad Cement, Chahak, and the Mashhad Power Plant connection."
                         "The substation also has ten 20 kV circuits that distribute power across a wide area in northern Mashhad."

                         "# Fuel System"
                         "The primary fuel for the power plant is natural gas."
                         "Diesel is used as a backup fuel in case of reduced gas pressure."
                         "Diesel is transported to the plant by trucks, and a project to construct a liquid fuel pipeline is underway."
                         "The plant has a liquid fuel storage capacity of 50 million liters."
                         "# Maintenance and Repairs"
                         "For the GE-F9 units, semi-major maintenance is required after 24,000 hours of operation, and major maintenance is required after 48,000 hours of operation."
                         "RI maintenance is required after 200,000 hours of operation."


                         "Two units of the Shariati Power Plant successfully underwent RI maintenance in the years 1402 and 1403.";


std::string  documentStatus1 = "Overall Status of the Power Plant:"
                               "Power Generation: 362.8 MW"
                               "Active Units: Combined cycle (two F9 gas turbine units and one steam unit) + 3 out of 6 small-scale units"
                               "Fuel: Natural gas (liquid fuel reserve at 2.31%, in warning state)"
                               "Warning: Liquid fuel charging is required to prevent the combined cycle from being taken offline.";

std::string  documentStatus2 = "Environmental Conditions:"
                               "Humidity: 86.75%"
                               "Ambient Temperature: 7.61°C"
                               "Ambient Pressure: 0.89 bar";

// std::string  documentStatus3 = "Status of Turbine G17:"
// "Issue: Bearing No. 3 has deviated from normal operation, and its RMS value is directly related to ambient temperature."
// "Probable Cause: Instability in the oil film and changes in fluid viscosity."
// "Required Actions: Check oil viscosity and vibration frequency spectra.";

std::string  documentStatus4 = "Status of Turbine G18:"
                               "Overall Status: Satisfactory after recent repairs."
                               "Recent Issue: A few hours of shutdown due to the liquid fuel pump.";

std::string  documentStatus5 = "Status of the Steam Turbine Unit:"
                               "Overall Status: Standard"
                               "Key Point:Presence of high - frequency spectra in vibration acceleration signals."
                               "Required Actions: Analyze the spectra with blade rows and rotating components across all turbine stages to identify the root cause.";

std::string  documentStatus6 = "What is the overall power generation status of the Shahriati Mashhad Power Plant?"
                               "Answer: The Shahriati Mashhad Power Plant is currently generating 281 mw of electricity. This production includes gas units, steam units, and small-scale units."
                               "Details:"
                               "Gas units: 192 MW"
                               "Steam unit: 89 MW";

std::string  documentStatus7 = "What is the fuel status of the power plant?"
                               "Answer: The primary fuel used is natural gas, and the liquid fuel reserve is currently at 2%."
                               "warning: If the liquid fuel reserve drops below 0.5%, part of the power plant may be taken offline.";

std::string  documentStatus8 = "Is there any issue with the liquid fuel pumps?"
                               "Answer: Yes, the liquid fuel pump in Turbine G18 caused a few hours of shutdown last week. This issue has been resolved after repairs.";

std::string  documentStatus9 = "What is the status of maintenance and repairs at the power plant?"
                               "Answer: The power plant follows a periodic maintenance and repair schedule. The most recent repairs were performed on Turbine G18, and this unit is now in optimal condition.";

std::string  documentStatus10 = "Question: What is the condition of the thermocouples?"
                                "Sample Answer:"
                                "The condition of the thermocouples at the Shahriati Mashhad Power Plant is generally acceptable, but some thermocouples require inspection and replacement."
                                "Details:"
                                "Gas Unit Thermocouples:"
                                "- 90% of the thermocouples are functioning normally."
                                "- 10% of the thermocouples need replacement due to incorrect calibration or sensor failure."
                                "- Steam Unit Thermocouples:"
                                "- 85% of the thermocouples are in good condition."
                                "- 15% of the thermocouples require inspection and repair due to corrosion or heat-related damage.";

#endif // DOCUMENT_H
